#!/bin/bash
#SBATCH -J f90cmpl
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o cmpl-%A.out
#SBATCH -e cmpl-%A.err

# compile the fortran module for use analyzing simulation data
module load python/3.8.1
source # path to software, for example: /work/props/Rob/software/hoomd4.2.1-mod/hoomdmod4.2.1-venv/bin/activate 
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1
pip install charset_normalizer
gfortran -c -fPIC solvopt.f90
f2py -c --fcompiler=gfortran -I. solvopt.o -m fortranmod module_analysis_BD.f90

# NOTE: compilation will produce warnings that can safely be ignored:
#       - warn that you are using a deprecated version of NumPy API
#         (this is a known issue for f2py)
#       - warn that you have incompatible pointers, unused modules, and unused variables
#         associated with the poresize calculation; this is normal
