#!/bin/bash

#SBATCH -J anlyzBD
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-anlyz.out
#SBATCH -e %A-anlyz.err

# source into the virtual environment
module load python/3.8.1
source # path to software, for example: /work/props/Rob/software/hoomd4.2.1-mod/hoomdmod4.2.1-venv/bin/activate 

# load required modules
#module load python/3.8.1
module load cmake/3.18.1
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# run the analysis file
python sim-analysis-BD.py
