#!/bin/bash

#SBATCH -J anlyz
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH -t 24:00:00
##SBATCH -t 4-24:00:00
##SBATCH -p long
#SBATCH --mem=128Gb
#SBATCH -o %A-anlyz.out
#SBATCH -e %A-anlyz.err

start=$SECONDS

module load python/3.8.1
source # path to software, for example: /work/props/Rob/software/hoomd4.2.1-mod/hoomdmod4.2.1-venv/bin/activate 
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# run the analysis file(s)
#python sim-analysis-DPD.py
echo "----"
#python sim-networkCSV-DPD.py
echo "----"
python sim-voronoi-DPD.py

time=$((SECONDS-start))
echo The simulation ran for $((time / 86400))day"(s)" $(((time / 3600) % 24))hr"(s)" $(((time / 60) % 60))min $((time % 60))sec real "(wall clock)" time >&1
