#!/bin/bash
#SBATCH -J instl
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-instl.out
#SBATCH -e %A-instl.err

# obtain hoomd-blue if you don't already have it
#git clone git@github.com:procf/hoomd4.2.1-mod.git

# move out of the hoomd4.1-mod/scripts/install-update directory
#cd ../../../

# create new virtual environment to store hoomd-blue
module load python/3.8.1
python3 -m venv hoomdmod4.2.1BDshear-venv
source hoomdmod4.2.1BDshear-venv/bin/activate

# load required modules 
#module load python/3.8.1
module load cmake/3.18.1
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# install prereqs (pybind11, cereal, Eigen)
yes | python3 hoomd4.2.1-mod/hoomd-4.2.1-procf/install-prereq-headers.py

# compile and install hoomd-blue
# NOTE: make sure ENABLE_MPI=on
# NOTE: HPMC, METAL, and TESTING are unused and turned off to speed up install 
cmake -B build/hoomd -S hoomd4.2.1-mod/hoomd-4.2.1-procf -DENABLE_MPI=on -DBUILD_HPMC=off -DBUILD_METAL=off -DBUILD_TESTING=off
cmake --build build/hoomd
cmake --install build/hoomd

# install additional required py packages
pip install --upgrade pip
pip3 install numpy
pip3 install gsd
pip3 install matplotlib
