#!/bin/bash
#SBATCH -J updtr
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-updt.out
#SBATCH -e %A-updt.err

# move out of the hoomd4.2.1-mod/scripts/install-update directory
#cd ../../../

# source into the virtual environment
module load python/3.8.1
source hoomdmod4.2.1BDshear-venv/bin/activate

# load required modules
#module load python/3.8.1
module load cmake/3.18.1
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

#recompile and reinstall hoomd-blue
cmake --build build/hoomd
cmake --install build/hoomd
