#!/bin/bash

#SBATCH -J gelcheck
#SBATCH -n 1 -N 1
#SBATCH -t 24:00:00
##SBATCH -t 4-24:00:00
##SBATCH -p long
##SBATCH -o %A-gelcheck.out
##SBATCH -e %A-gelcheck.err
#SBATCH -o gelcheck-%A.out
#SBATCH -e gelcheck-%A.err

start=$SECONDS

# source into the virtual environment
module load python/3.8.1
source /work/props/Rob/software/hoomd4.2.1-mod-rob/hoomdmod4.2.1-rob-venv/bin/activate
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# run the analysis file(s)
python sim-gelcheck.py


time=$((SECONDS-start))
echo The simulation ran for $((time / 86400))day"(s)" $(((time / 3600) % 24))hr"(s)" $(((time / 60) % 60))min $((time % 60))sec real "(wall clock)" time >&1
