#!/bin/bash

#SBATCH -J anlyzDPD
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-anlyz.out
#SBATCH -e %A-anlyz.err
##SBATCH -o anlyz-%A.out
##SBATCH -e anlyz-%A.err

# compile the fortran module for use analyzing simulation data
#module load python/3.8.1
#f2py -c module_analysis.f90 -m module

# source into the virtual environment
module load python/3.8.1
source /work/props/Rob/software/hoomd-annot/hoomdmod-venv/bin/activate

# load required modules
#module load python/3.8.1
module load cmake/3.18.1
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# run the analysis file
python sim-shear-analysis-DPD.py
