#!/bin/bash

#SBATCH -J PYpkg
#SBATCH -n 1 -N 1
#SBATCH -t 24:00:00
#SBATCH --mem=128Gb
#SBATCH -o pkg-%A.out
#SBATCH -e pkg-%A.err

start=$SECONDS

module load python/3.8.1
source /work/props/Rob/software/hoomd4.2.1-mod/hoomdmod4.2.1-venv/bin/activate 
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# install required packages for analyses
pip install --upgrade pip
pip install pandas
pip install networkx
pip install pyvoro 
pip install scipy 

time=$((SECONDS-start))
echo The simulation ran for $((time / 86400))day"(s)" $(((time / 3600) % 24))hr"(s)" $(((time / 60) % 60))min $((time % 60))sec real "(wall clock)" time >&1
