#!/bin/bash
#SBATCH -J shearDPD
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=27
#SBATCH --cpus-per-task=1
#SBATCH -t 24:00:00
##SBATCH -t 4-24:00:00
##SBATCH -p long
#SBATCH --constraint=ib
##SBATCH --mem=128Gb
#SBATCH -o %A.out
#SBATCH -e %A.err

start=$SECONDS

module purge
module load python/3.8.1
source # path to software, for example: /work/props/Rob/software/hoomd4.2.1-mod/hoomdmod4.2.1-venv/bin/activate 
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1
mpirun python3 sim-shear-DPD.py

time=$((SECONDS-start))
echo The simulation ran for $((time / 86400))day"(s)" $(((time / 3600) % 24))hr"(s)" $(((time / 60) % 60))min $((time % 60))sec real "(wall clock)" time >&1
